# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np
a = np.zeros(100)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [107]:
a = np.ones(100)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [3]:
import numpy as np
a = np.full(100, 3)
print(a)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [5]:
import numpy; 
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [106]:
A = np.arange(25).reshape(5,5)
print(A)
A[1], A[2] = A[2], A[1]
print(f"changed: {A}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
changed: [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 6. Создать вектор со значениями от 10 до 100

In [105]:
Z = np.arange(10, 101)
print(Z)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 7. Развернуть вектор (первый становится последним)

In [104]:
Z = np.arange(0, 10)
print(Z)
Z = Z[::-1]
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [103]:
A = np.arange(0, 16).reshape(4, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [102]:
Z = np.arange(0, 6)
print(A)
zeroes_between = 3
Z0 = np.zeros((len(Z)-1)*zeroes_between + len(Z))
print(Z0)
Z0[::zeroes_between+1] = Z
print(Z0)

[[[0.64925251 0.77890812 0.8154477 ]
  [0.161633   0.2131229  0.07015306]
  [0.98625726 0.44636328 0.75102197]]

 [[0.12527203 0.76855276 0.15280834]
  [0.58492042 0.59049922 0.0182695 ]
  [0.61667728 0.91023404 0.70230685]]

 [[0.42580191 0.51717633 0.84178443]
  [0.32147427 0.71900617 0.85118333]
  [0.34393474 0.48982192 0.03930504]]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [101]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [100]:
A = np.random.random((3,3,3))
print(A)

[[[0.64925251 0.77890812 0.8154477 ]
  [0.161633   0.2131229  0.07015306]
  [0.98625726 0.44636328 0.75102197]]

 [[0.12527203 0.76855276 0.15280834]
  [0.58492042 0.59049922 0.0182695 ]
  [0.61667728 0.91023404 0.70230685]]

 [[0.42580191 0.51717633 0.84178443]
  [0.32147427 0.71900617 0.85118333]
  [0.34393474 0.48982192 0.03930504]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [99]:
A = np.random.random((10, 10))
min, max = A.min(), A.max()
print(min, max)

0.0025156689541192545 0.9910801373783713


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [98]:
Z = np.random.random((30))
z_mean = Z.mean()
print(z_mean)

0.48256424497510136


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [94]:
Z = np.ones((3,3))
print(Z)
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [111]:
Z = np.diag([1,2,2,4], k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [115]:
Z = np.zeros((8,8))
Z[::2, 1::2], Z[1::2, ::2] = 1, 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [117]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [125]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [127]:
A = np.arange(15).reshape(5,3)
B = np.arange(6).reshape(3,2)
print(A)
print(B)

C = np.dot(A, B)
print(C)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [137]:
arr = np.arange(11)
print(arr)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

#### 26. Отсортировать вектор

#### 27. Проверить, одинаковы ли 2 numpy массива

#### 28. Сделать массив неизменяемым

#### 29. Найти n наибольших значений в массиве

#### 30. Заменить максимальный элемент на ноль

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

#### 34. Напечатать все значения в массиве

#### 35. Найти ближайшее к заданному значению число в заданном массиве

#### 36. Преобразовать массив из float в int

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

#### 40. Отсортировать матрицу по n-ому столбцу

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям